 # Writing Efficient Code:
 
 1. Minimal Completion time (Fast Runtime)
 2. Minimal Resources Consumption (Small memory FOotprint)

In [2]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

## Bad Code: 

In [5]:
# Print the list created using the Non-Pythonic approach
i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


## Better Code:

In [8]:
# Print the list created by looping over the contents of names
better_list = []
for name in names:
    if len(name) >= 6:
        better_list.append(name)
print(better_list)

['Kramer', 'Elaine', 'George', 'Newman']


## Best Code:

In [9]:
# Print the list created by using list comprehension
best_list = [name for name in names if len(name) >= 6]
print(best_list)

['Kramer', 'Elaine', 'George', 'Newman']


## The Zen of Python:


In [10]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# Building with Built-Ins: 

In [11]:
# Create a range object that goes from 0 to 5
nums = range(0,6)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 11 by unpacking a range object
nums_list2 = [*range(1,12,2)]  # ** Sterik is noticeable :
print(nums_list2)

<class 'range'>
[0, 1, 2, 3, 4, 5]
[1, 3, 5, 7, 9, 11]


In [14]:
# nums_list2 = [range(1,12,2)]
# print(nums_list2)
# nums_list2 = [*range(1,12,2)]
# print(nums_list2)

[range(1, 12, 2)]
[1, 3, 5, 7, 9, 11]


## Good and Bad Code Using Enumerate Function: 

### Bad: 

In [18]:
# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]


###  Good:

In [19]:
# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]


### Best:

In [21]:
# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, start=1)]
print(indexed_names_unpack)

[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


## Map Function: 

### Bad Code: 

In [23]:
names_uppercase = []

for name in names:
  names_uppercase.append(name.upper())
print(names_uppercase)

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


###  Good Code:

In [37]:
[name.upper() for name in names]

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']

In [38]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*names_map]

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


In [46]:
print(names_map) # We can not print map function directly.

In [48]:
[*range(10)]  # STERIK is use to print itterative object in list directly. 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## The Power of Numpy.

In [5]:
import numpy as np
# Element of Numpy array should be same data type.

In [6]:
nums = np.array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [8]:
# Print second row of nums
print(nums[1,:])
 
# Print all elements of nums that are greater than six
print(nums[nums > 6])

# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

[ 8  9 10 11 12]
[ 7  8  9 10 11 12]
[[ 6  8 10 12 14]
 [16 18 20 22 24]]
[[ 3  4  6  6  7]
 [ 8  9 11 11 12]]


In [39]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

In [44]:
def welcome_guest(name):
    return("Welcome...",guest_arrivals )

In [45]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)

guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')

('Welcome...', [('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)])
('Welcome...', [('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)])
('Welcome...', [('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)])
('Welcome...', [('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)])
('Welcome...', [('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)])
